export enum GROUP {
  BACKGROUND = "Background",
  BORDER = "Border",
  EFFECTS = "Effects",
  INTERACTIVITY = "Interactivity",
  LAYOUT = "Layout",
  POSITION = "Position",
  SIZE = "Size",
  SPACING = "Spacing",
  SVG = "SVG",
  TYPOGRAPHY = "Typography"
}

// TODO groups should be by property instead of className
export const classNameGroups: {
  [pattern: string]: string;
} = {
  "-m-": GROUP.SPACING,
  "-mb-": GROUP.SPACING,
  "-ml-": GROUP.SPACING,
  "-mr-": GROUP.SPACING,
  "-mt-": GROUP.SPACING,
  "-mx-": GROUP.SPACING,
  "-my-": GROUP.SPACING,
  "absolute": GROUP.POSITION,
  "align-": GROUP.LAYOUT,
  "antialiased": GROUP.TYPOGRAPHY,
  "appearance-none": GROUP.INTERACTIVITY,
  "bg-": GROUP.BACKGROUND,
  "block": GROUP.LAYOUT,
  "border": GROUP.BORDER,
  "bottom-": GROUP.POSITION,
  "break-": GROUP.TYPOGRAPHY,
  "capitalize": GROUP.TYPOGRAPHY,
  "container": GROUP.SIZE,
  "content-": GROUP.LAYOUT,
  "cursor-": GROUP.INTERACTIVITY,
  "fill-current": GROUP.SVG,
  "m-": GROUP.SPACING,
  "mb-": GROUP.SPACING,
  "ml-": GROUP.SPACING,
  "mr-": GROUP.SPACING,
  "mt-": GROUP.SPACING,
  "mx-": GROUP.SPACING,
  "my-": GROUP.SPACING,
  "fixed": GROUP.POSITION,
  "flex": GROUP.LAYOUT,
  "float": GROUP.POSITION,
  "font-": GROUP.TYPOGRAPHY,
  "h-": GROUP.SIZE,
  "hidden": GROUP.LAYOUT,
  "inline": GROUP.LAYOUT,
  "inset-": GROUP.POSITION,
  "invisible": GROUP.LAYOUT,
  "italic": GROUP.TYPOGRAPHY,
  "items-": GROUP.LAYOUT,
  "justify-": GROUP.LAYOUT,
  "leading-": GROUP.TYPOGRAPHY,
  "left-": GROUP.POSITION,
  "line-through": GROUP.TYPOGRAPHY,
  "list-": GROUP.TYPOGRAPHY,
  "lowercase": GROUP.TYPOGRAPHY,
  "max-": GROUP.SIZE,
  "min-": GROUP.SIZE,
  "no-underline": GROUP.TYPOGRAPHY,
  "normal-case": GROUP.TYPOGRAPHY,
  "not-italic": GROUP.TYPOGRAPHY,
  "object-": GROUP.LAYOUT,
  "opacity-": GROUP.EFFECTS,
  "order-": GROUP.LAYOUT,
  "outline-": GROUP.INTERACTIVITY,
  "overflow-": GROUP.LAYOUT,
  "p-": GROUP.SPACING,
  "pb-": GROUP.SPACING,
  "pl-": GROUP.SPACING,
  "pointer-events-": GROUP.INTERACTIVITY,
  "pr-": GROUP.SPACING,
  "pt-": GROUP.SPACING,
  "px-": GROUP.SPACING,
  "py-": GROUP.SPACING,
  "relative": GROUP.POSITION,
  "resize": GROUP.INTERACTIVITY,
  "right-": GROUP.POSITION,
  "rounded": GROUP.BORDER,
  "scrolling-": GROUP.LAYOUT,
  "select-": GROUP.INTERACTIVITY,
  "self-": GROUP.LAYOUT,
  "shadow": GROUP.EFFECTS,
  "stroke-": GROUP.SVG,
  "subpixel": GROUP.TYPOGRAPHY,
  "static": GROUP.POSITION,
  "sticky": GROUP.POSITION,
  "table": GROUP.LAYOUT,
  "text-": GROUP.TYPOGRAPHY,
  "top-": GROUP.POSITION,
  "tracking-": GROUP.TYPOGRAPHY,
  "truncate": GROUP.TYPOGRAPHY,
  "underline": GROUP.TYPOGRAPHY,
  "uppercase": GROUP.TYPOGRAPHY,
  "visible": GROUP.LAYOUT,
  "w-": GROUP.SIZE,
  "whitespace-": GROUP.TYPOGRAPHY,
  "z-": GROUP.POSITION
};
